# Generated by Django 5.1.2 on 2024-11-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_customuser_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default=2002),
            preserve_default=False,
        ),
    ]
